### ISSUE TITLE
recognize gitlab URLs

### ISSUE THREAD

**Issue by anarcat** [weaselp/ticketbot#15]
zwiebelbot doesn't seem to recognize gitlab bug URLs even though the provider is configured. example:

```
15:41:09 <anarcat> i wonder if we could https://gitlab.torproject.org/tpo/tpa/services/-/issues/29423
15:42:37 <anarcat> tpo/tpa/services#29423
15:42:38 -zwiebelbot:#tpo-admin- gitlabtpo:tpo/tpa/services#29423: Enable search for non-logged in users on trac - 
          https://gitlab.torproject.org/tpo/tpa/services/-/issues/29423
```

the first URL should have triggered the bot, but didn't... not sure what's going on here, maybe the regex is wrong?

**Comment by weaselp** [comment]
There is no regex matching the URL.  Therefore, it doesn't trigger.
