### ISSUE TITLE
make #NNN point to gitlab/legacy in tor channels

### ISSUE THREAD

**Issue by anarcat** [weaselp/ticketbot#16]
since b20ecd28 and b56de94ee8e84f005908bd414035ca74c9014996, the default "trac" provider has been removed. it was serving queries such as `#NNN` and redirecting them to trac. 

one of the goals of #14 was to change that to point to the gitlab legacy project at https://gitlab.torproject.org/legacy/trac/-/issues instead. yet it seems like it's not working:

```
09:08:39 <anarcat> this this work yet? https://gitlab.torproject.org/tpo/tpa/gitlab/-/issues/2
09:08:40 -zwiebelbot:#tpo-admin- tor:tpo/tpa/gitlab#2: zwiebelbot doesn't talk with the new gitlab server - https://bugs.torproject.org/tpo/tpa/gitlab/2
09:08:51 <anarcat> tpo/tpa/gitlab#1
09:08:51 -zwiebelbot:#tpo-admin- tor:tpo/tpa/gitlab#1: legacy issues are writable and should not be - https://bugs.torproject.org/tpo/tpa/gitlab/1
09:09:01 <anarcat> #29423
09:09:14 <anarcat> #34134
09:17:02 <anarcat> legacy/trac#34134
09:17:03 -zwiebelbot:#tpo-admin- tor:legacy/trac#34134: yahoo hates tor-announce mails: "User is receiving mail too quickly" - 
          https://bugs.torproject.org/legacy/trac/34134
```

i don't understand how the `#` shortcut gets activated, so I don't understand how to fix this, unfortunately.

**Comment by weaselp** [comment]
I think this already worked in tor channels, but not in the unlisted not "#tor*" channels.
